### PR TITLE
Dbeard swift

### PR DESCRIPTION
**Pull request by daniel-beard**

### CODE REVIEW

**Comment by justinweiss** [comment]
This is really neat! Great stuff.

I wonder if it would make sense to put into its own gem -- that way, it wouldn't have to wait for robot updates to be released.

**Comment by daniel-beard** [comment]
Oh wow, I hadn't realized I'd opened this PR against this repo! Thanks for the feedback. I'm looking into proper resource restrictions right now, hoping to have something more polished by the end of next week.

Is there a way for robut to comment asynchronously? E.g. if I wanted to run these as part of a redis queue?

**Comment by justinweiss** [comment]
Not natively -- It *might* work to spin off a thread, but I don't remember how well that works. It's worth experimenting with, though!

**Comment by daniel-beard** [comment]
Cool, thanks. I'll try experimenting with redis and see what I can come up with.

**Pull request closed without merging**
